name: Payment-services Pipeline

on:
  push:
    paths:
      - 'services/payments/**'
      - 'k8s/deployments/payment-deployment.yaml'
      - 'k8s/services/payment-service.yaml'
      - '.github/workflows/payment-pipeline.yml'
      - 'k8s/hpa/payment-hpa.yaml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      RESOURCE_GROUP: briitzresourcegroup
      AKS_CLUSTER: briitzaks
      ACR_NAME: briitzacr

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and push docker image with SHA commit
        run: |
          IMAGE_TAG=${{github.sha}}
          IMAGE_NAME=$ACR_NAME.azurecr.io/microservices-payments:$IMAGE_TAG
          docker build -t $IMAGE_NAME -f ./services/payments/Dockerfile services/payments
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'


      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing


      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/services/payment-service.yaml -n briitz
          kubectl apply -f k8s/deployments/payment-deployment.yaml -n briitz
          kubectl set image deployment/payment-deployment payment=${{ env.IMAGE_NAME }} -n briitz
          kubectl rollout status deployment/payment-deployment -n briitz

      - name: Deploy scaling policy
        run: |
          kubectl apply -f k8s/hpa/payment-hpa.yaml -n briitz
          kubectl get hpa payment-hpa -n briitz