name: Product-service Pipeline

on:
  push:
    paths:
      - 'services/products/**'
      - 'k8s/product-deployment.yaml'
      - 'k8s/product-service.yaml'
      - '.github/workflows/product-pipeline.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build and push Docker
        run: |
          docker build -t briitzacr.azurecr.io/microservices-products:latest -f ./services/products/Dockerfile services/products
          docker push briitzacr.azurecr.io/microservices-products:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/product-deployment.yaml
          kubectl apply -f k8s/product-service.yaml



          